// Code generated by hertz generator.

package main

import (
	"time"

	"github.com/cold-runner/skylark/biz/application/event"
	"github.com/cold-runner/skylark/biz/config"
	"github.com/cold-runner/skylark/biz/infrastructure"
	"github.com/cold-runner/skylark/biz/util"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// 初始化配置
	config.Init()
	// 初始化基础设施
	infrastructure.Init()
	// 将数据库文章上传至全文搜索引擎中
	gopool.Go(event.SyncToSearchEngine)

	serverConf := config.GetConfig().GetServer()

	h := server.Default(
		server.WithExitWaitTime(serverConf.ExitWaitTime*time.Second),
		server.WithHostPorts(serverConf.Host+":"+serverConf.Port),

		//server.WithTracer(prometheus.NewServerTracer(":9091", "/hertz")),
		server.WithCustomValidator(util.CustomValidator()),
	)
	// pprof
	//pprof.Register(h)
	// 注册路由
	register(h)
	// 启动服务
	h.Spin()
}
