// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/cold-runner/skylark/biz/infrastructure/store/orm_gen"
)

func newPost(db *gorm.DB, opts ...gen.DOOption) post {
	_post := post{}

	_post.postDo.UseDB(db, opts...)
	_post.postDo.UseModel(&orm_gen.Post{})

	tableName := _post.postDo.TableName()
	_post.ALL = field.NewAsterisk(tableName)
	_post.ID = field.NewField(tableName, "id")
	_post.CreatedAt = field.NewTime(tableName, "created_at")
	_post.DeletedAt = field.NewField(tableName, "deleted_at")
	_post.UpdatedAt = field.NewTime(tableName, "updated_at")
	_post.Title = field.NewString(tableName, "title")
	_post.CoverImage = field.NewString(tableName, "cover_image")
	_post.UserID = field.NewString(tableName, "user_id")
	_post.Summary = field.NewString(tableName, "summary")
	_post.Content = field.NewString(tableName, "content")
	_post.CategorieID = field.NewString(tableName, "categorie_id")
	_post.Temperature = field.NewInt64(tableName, "temperature")
	_post.LikeCount = field.NewInt64(tableName, "like_count")
	_post.ViewCount = field.NewInt64(tableName, "view_count")
	_post.StarCount = field.NewInt64(tableName, "star_count")
	_post.CommentCount = field.NewInt64(tableName, "comment_count")
	_post.ShareCount = field.NewInt64(tableName, "share_count")
	_post.State = field.NewInt64(tableName, "state")
	_post.LinkURL = field.NewString(tableName, "link_url")

	_post.fillFieldMap()

	return _post
}

// post 博文
type post struct {
	postDo

	ALL          field.Asterisk
	ID           field.Field  // 自然主键
	CreatedAt    field.Time   // 创建时间
	DeletedAt    field.Field  // 删除时间（软删除）
	UpdatedAt    field.Time   // 更新时间
	Title        field.String // 博文标题
	CoverImage   field.String // 博文标题配图
	UserID       field.String // 作者id
	Summary      field.String // 博文概览
	Content      field.String // 博文内容
	CategorieID  field.String // 隶属哪个归档
	Temperature  field.Int64  // 博文热度（排序文章时用）
	LikeCount    field.Int64  // 博文点赞量
	ViewCount    field.Int64  // 观看量
	StarCount    field.Int64  // 收藏数量
	CommentCount field.Int64
	ShareCount   field.Int64  // 分享数量
	State        field.Int64  // 文章状态：0审核中、1通过、2被举报
	LinkURL      field.String // 文章外部链接

	fieldMap map[string]field.Expr
}

func (p post) Table(newTableName string) *post {
	p.postDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p post) As(alias string) *post {
	p.postDo.DO = *(p.postDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *post) updateTableName(table string) *post {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewField(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.Title = field.NewString(table, "title")
	p.CoverImage = field.NewString(table, "cover_image")
	p.UserID = field.NewString(table, "user_id")
	p.Summary = field.NewString(table, "summary")
	p.Content = field.NewString(table, "content")
	p.CategorieID = field.NewString(table, "categorie_id")
	p.Temperature = field.NewInt64(table, "temperature")
	p.LikeCount = field.NewInt64(table, "like_count")
	p.ViewCount = field.NewInt64(table, "view_count")
	p.StarCount = field.NewInt64(table, "star_count")
	p.CommentCount = field.NewInt64(table, "comment_count")
	p.ShareCount = field.NewInt64(table, "share_count")
	p.State = field.NewInt64(table, "state")
	p.LinkURL = field.NewString(table, "link_url")

	p.fillFieldMap()

	return p
}

func (p *post) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *post) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 18)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["title"] = p.Title
	p.fieldMap["cover_image"] = p.CoverImage
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["summary"] = p.Summary
	p.fieldMap["content"] = p.Content
	p.fieldMap["categorie_id"] = p.CategorieID
	p.fieldMap["temperature"] = p.Temperature
	p.fieldMap["like_count"] = p.LikeCount
	p.fieldMap["view_count"] = p.ViewCount
	p.fieldMap["star_count"] = p.StarCount
	p.fieldMap["comment_count"] = p.CommentCount
	p.fieldMap["share_count"] = p.ShareCount
	p.fieldMap["state"] = p.State
	p.fieldMap["link_url"] = p.LinkURL
}

func (p post) clone(db *gorm.DB) post {
	p.postDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p post) replaceDB(db *gorm.DB) post {
	p.postDo.ReplaceDB(db)
	return p
}

type postDo struct{ gen.DO }

type IPostDo interface {
	gen.SubQuery
	Debug() IPostDo
	WithContext(ctx context.Context) IPostDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPostDo
	WriteDB() IPostDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPostDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPostDo
	Not(conds ...gen.Condition) IPostDo
	Or(conds ...gen.Condition) IPostDo
	Select(conds ...field.Expr) IPostDo
	Where(conds ...gen.Condition) IPostDo
	Order(conds ...field.Expr) IPostDo
	Distinct(cols ...field.Expr) IPostDo
	Omit(cols ...field.Expr) IPostDo
	Join(table schema.Tabler, on ...field.Expr) IPostDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPostDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPostDo
	Group(cols ...field.Expr) IPostDo
	Having(conds ...gen.Condition) IPostDo
	Limit(limit int) IPostDo
	Offset(offset int) IPostDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPostDo
	Unscoped() IPostDo
	Create(values ...*orm_gen.Post) error
	CreateInBatches(values []*orm_gen.Post, batchSize int) error
	Save(values ...*orm_gen.Post) error
	First() (*orm_gen.Post, error)
	Take() (*orm_gen.Post, error)
	Last() (*orm_gen.Post, error)
	Find() ([]*orm_gen.Post, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*orm_gen.Post, err error)
	FindInBatches(result *[]*orm_gen.Post, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*orm_gen.Post) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPostDo
	Assign(attrs ...field.AssignExpr) IPostDo
	Joins(fields ...field.RelationField) IPostDo
	Preload(fields ...field.RelationField) IPostDo
	FirstOrInit() (*orm_gen.Post, error)
	FirstOrCreate() (*orm_gen.Post, error)
	FindByPage(offset int, limit int) (result []*orm_gen.Post, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPostDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p postDo) Debug() IPostDo {
	return p.withDO(p.DO.Debug())
}

func (p postDo) WithContext(ctx context.Context) IPostDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p postDo) ReadDB() IPostDo {
	return p.Clauses(dbresolver.Read)
}

func (p postDo) WriteDB() IPostDo {
	return p.Clauses(dbresolver.Write)
}

func (p postDo) Session(config *gorm.Session) IPostDo {
	return p.withDO(p.DO.Session(config))
}

func (p postDo) Clauses(conds ...clause.Expression) IPostDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p postDo) Returning(value interface{}, columns ...string) IPostDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p postDo) Not(conds ...gen.Condition) IPostDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p postDo) Or(conds ...gen.Condition) IPostDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p postDo) Select(conds ...field.Expr) IPostDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p postDo) Where(conds ...gen.Condition) IPostDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p postDo) Order(conds ...field.Expr) IPostDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p postDo) Distinct(cols ...field.Expr) IPostDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p postDo) Omit(cols ...field.Expr) IPostDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p postDo) Join(table schema.Tabler, on ...field.Expr) IPostDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p postDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPostDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p postDo) RightJoin(table schema.Tabler, on ...field.Expr) IPostDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p postDo) Group(cols ...field.Expr) IPostDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p postDo) Having(conds ...gen.Condition) IPostDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p postDo) Limit(limit int) IPostDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p postDo) Offset(offset int) IPostDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p postDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPostDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p postDo) Unscoped() IPostDo {
	return p.withDO(p.DO.Unscoped())
}

func (p postDo) Create(values ...*orm_gen.Post) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p postDo) CreateInBatches(values []*orm_gen.Post, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p postDo) Save(values ...*orm_gen.Post) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p postDo) First() (*orm_gen.Post, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*orm_gen.Post), nil
	}
}

func (p postDo) Take() (*orm_gen.Post, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*orm_gen.Post), nil
	}
}

func (p postDo) Last() (*orm_gen.Post, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*orm_gen.Post), nil
	}
}

func (p postDo) Find() ([]*orm_gen.Post, error) {
	result, err := p.DO.Find()
	return result.([]*orm_gen.Post), err
}

func (p postDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*orm_gen.Post, err error) {
	buf := make([]*orm_gen.Post, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p postDo) FindInBatches(result *[]*orm_gen.Post, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p postDo) Attrs(attrs ...field.AssignExpr) IPostDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p postDo) Assign(attrs ...field.AssignExpr) IPostDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p postDo) Joins(fields ...field.RelationField) IPostDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p postDo) Preload(fields ...field.RelationField) IPostDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p postDo) FirstOrInit() (*orm_gen.Post, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*orm_gen.Post), nil
	}
}

func (p postDo) FirstOrCreate() (*orm_gen.Post, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*orm_gen.Post), nil
	}
}

func (p postDo) FindByPage(offset int, limit int) (result []*orm_gen.Post, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p postDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p postDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p postDo) Delete(models ...*orm_gen.Post) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *postDo) withDO(do gen.Dao) *postDo {
	p.DO = *do.(*gen.DO)
	return p
}
