// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCategorie = "categorie"

// Categorie mapped from table <categorie>
type Categorie struct {
	ID            int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_categories_deleted_at,priority:1" json:"deleted_at"`
	BackGroundURL string         `gorm:"column:back_ground_url;type:longtext" json:"back_ground_url"`
	Name          string         `gorm:"column:name;type:longtext" json:"name"`
	Rank          int64          `gorm:"column:rank;type:bigint" json:"rank"`
	PlateID       int64          `gorm:"column:plate_id;type:bigint unsigned" json:"plate_id"`
}

// TableName Categorie's table name
func (*Categorie) TableName() string {
	return TableNameCategorie
}
