// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDraft = "draft"

// Draft mapped from table <draft>
type Draft struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_stored_drafts_deleted_at,priority:1" json:"deleted_at"`
	Title     string         `gorm:"column:title;type:longtext" json:"title"`
	Content   string         `gorm:"column:content;type:longtext" json:"content"`
	UserID    int64          `gorm:"column:user_id;type:bigint unsigned" json:"user_id"`
}

// TableName Draft's table name
func (*Draft) TableName() string {
	return TableNameDraft
}
