// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEssay = "essay"

// Essay mapped from table <essay>
type Essay struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;comment:自然主键" json:"id"`                                     // 自然主键
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`                     // 创建时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间（软删除）" json:"deleted_at"`                         // 删除时间（软删除）
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                              // 更新时间
	Content     string         `gorm:"column:content;type:text;not null;comment:随笔内容" json:"content"`                               // 随笔内容
	TopicID     int64          `gorm:"column:topic_id;type:bigint;index:essay_topic_id_fk,priority:1;comment:所属话题" json:"topic_id"` // 所属话题
	UserID      int64          `gorm:"column:user_id;type:bigint;not null;comment:随笔作者（考虑性能，不加外键）" json:"user_id"`                  // 随笔作者（考虑性能，不加外键）
	Temperature int64          `gorm:"column:temperature;type:bigint unsigned;not null;comment:随笔热度（排序时用）" json:"temperature"`      // 随笔热度（排序时用）
	Click       int64          `gorm:"column:click;type:bigint unsigned;not null;comment:点击量（计算热度时用）" json:"click"`                 // 点击量（计算热度时用）
}

// TableName Essay's table name
func (*Essay) TableName() string {
	return TableNameEssay
}
