// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLark = "lark"

// Lark mapped from table <lark>
type Lark struct {
	ID            int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_larks_deleted_at,priority:1" json:"deleted_at"`
	StuNum        string         `gorm:"column:stu_num;type:char(8);not null;uniqueIndex:stu_num,priority:1" json:"stu_num"`
	Name          string         `gorm:"column:name;type:varchar(191);not null" json:"name"`
	Password      string         `gorm:"column:password;type:varchar(191)" json:"password"`
	Gender        int64          `gorm:"column:gender;type:tinyint(1)" json:"gender"`
	College       string         `gorm:"column:college;type:char(16);not null" json:"college"`
	Major         string         `gorm:"column:major;type:char(30);not null" json:"major"`
	Grade         string         `gorm:"column:grade;type:varchar(3);not null" json:"grade"`
	StuCardURL    string         `gorm:"column:stu_card_url;type:varchar(191);not null" json:"stu_card_url"`
	Phone         string         `gorm:"column:phone;type:char(11);not null;uniqueIndex:phone,priority:1" json:"phone"`
	Province      string         `gorm:"column:province;type:varchar(3)" json:"province"`
	Age           int64          `gorm:"column:age;type:tinyint unsigned" json:"age"`
	Birth         time.Time      `gorm:"column:birth;type:date" json:"birth"`
	PhotoURL      string         `gorm:"column:photo_url;type:varchar(191)" json:"photo_url"`
	Email         string         `gorm:"column:email;type:varchar(191);uniqueIndex:email,priority:1" json:"email"`
	Introduce     string         `gorm:"column:introduce;type:text" json:"introduce"`
	Avatar        string         `gorm:"column:avatar;type:varchar(191)" json:"avatar"`
	QqUnionID     string         `gorm:"column:qq_union_id;type:varchar(191);uniqueIndex:qq_union_id,priority:1" json:"qq_union_id"`
	WechatUnionID string         `gorm:"column:wechat_union_id;type:varchar(191);uniqueIndex:wechat_union_id,priority:1" json:"wechat_union_id"`
	Legal         int64          `gorm:"column:legal;type:tinyint" json:"legal"`
	State         *int64         `gorm:"column:state;type:tinyint(1);default:1" json:"state"`
}

// TableName Lark's table name
func (*Lark) TableName() string {
	return TableNameLark
}
