// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLearningPost = "learning_posts"

// LearningPost mapped from table <learning_posts>
type LearningPost struct {
	Title       string         `gorm:"column:title;type:longtext" json:"title"`
	PictureURL  string         `gorm:"column:picture_url;type:longtext" json:"picture_url"`
	UserID      int64          `gorm:"column:user_id;type:bigint unsigned" json:"user_id"`
	Summary     string         `gorm:"column:summary;type:longtext" json:"summary"`
	Content     string         `gorm:"column:content;type:longtext" json:"content"`
	IsDraft     int64          `gorm:"column:is_draft;type:tinyint(1)" json:"is_draft"`
	Theme       string         `gorm:"column:theme;type:longtext" json:"theme"`
	Tag         string         `gorm:"column:tag;type:varchar(100)" json:"tag"`
	ID          int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_stored_learning_posts_deleted_at,priority:1" json:"deleted_at"`
	Temperature int64          `gorm:"column:temperature;type:bigint unsigned" json:"temperature"`
	Like        int64          `gorm:"column:like;type:bigint" json:"like"`
	Watch       int64          `gorm:"column:watch;type:bigint" json:"watch"`
	Star        int64          `gorm:"column:star;type:bigint unsigned" json:"star"`
	Pass        int64          `gorm:"column:pass;type:tinyint(1)" json:"pass"`
	Report      int64          `gorm:"column:report;type:tinyint(1)" json:"report"`
}

// TableName LearningPost's table name
func (*LearningPost) TableName() string {
	return TableNameLearningPost
}
