// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePostTag = "post_tag"

// PostTag mapped from table <post_tag>
type PostTag struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;comment:自然主键" json:"id"`                                     // 自然主键
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`                     // 创建时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间（软删除）" json:"deleted_at"`                         // 删除时间（软删除）
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                              // 更新时间
	TagID     int64          `gorm:"column:tag_id;type:bigint;index:post_tag_tag_id_fk,priority:1;comment:文章所属标签" json:"tag_id"`  // 文章所属标签
	PostID    int64          `gorm:"column:post_id;type:bigint;index:post_tag_post_id_fk,priority:1;comment:博文id" json:"post_id"` // 博文id
}

// TableName PostTag's table name
func (*PostTag) TableName() string {
	return TableNamePostTag
}
