// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTopicLike = "topic_like"

// TopicLike mapped from table <topic_like>
type TopicLike struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;comment:自然主键" json:"id"`                      // 自然主键
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`      // 创建时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间（软删除）" json:"deleted_at"`          // 删除时间（软删除）
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`               // 更新时间
	TopicID   int64          `gorm:"column:topic_id;type:bigint;not null;comment:话题id（考虑性能，不加外键）" json:"topic_id"` // 话题id（考虑性能，不加外键）
	UserID    int64          `gorm:"column:user_id;type:bigint;not null;comment:点赞人（考虑性能，不加外键）" json:"user_id"`    // 点赞人（考虑性能，不加外键）
}

// TableName TopicLike's table name
func (*TopicLike) TableName() string {
	return TableNameTopicLike
}
