// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTopic = "topic"

// Topic mapped from table <topic>
type Topic struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;comment:自然主键" json:"id"`                                         // 自然主键
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`                         // 创建时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间（软删除）" json:"deleted_at"`                             // 删除时间（软删除）
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                                  // 更新时间
	Name      string         `gorm:"column:name;type:varchar(50);not null;uniqueIndex:topic_pk2,priority:1;comment:话题名称" json:"name"` // 话题名称
}

// TableName Topic's table name
func (*Topic) TableName() string {
	return TableNameTopic
}
