// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserInteraction = "user_interaction"

// UserInteraction mapped from table <user_interaction>
type UserInteraction struct {
	ID         int64          `gorm:"column:id;type:bigint;primaryKey;comment:自然主键" json:"id"`                                                                 // 自然主键
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`                                                 // 创建时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间（软删除）" json:"deleted_at"`                                                     // 删除时间（软删除）
	UserID     int64          `gorm:"column:user_id;type:bigint;not null;index:user_interaction_lark_id_fk,priority:1;comment:subject" json:"user_id"`         // subject
	FollowedID int64          `gorm:"column:followed_id;type:bigint;not null;index:user_interaction_lark_id_fk2,priority:1;comment:object" json:"followed_id"` // object
}

// TableName UserInteraction's table name
func (*UserInteraction) TableName() string {
	return TableNameUserInteraction
}
