// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

import "github.com/google/uuid"

const TableNameCommentLike = "comment_like"

// CommentLike 评论点赞表
type CommentLike struct {
	ID        uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4();comment:自然主键" json:"id"`                                        // 自然主键
	CommentID string    `gorm:"column:comment_id;type:varchar(255);not null;index:comment_like_comment_id_fk,priority:1;comment:评论id" json:"comment_id"` // 评论id
	UserID    string    `gorm:"column:user_id;type:varchar(255);not null;index:comment_like_lark_id_fk,priority:1;comment:评论者id" json:"user_id"`         // 评论者id
}

// TableName CommentLike's table name
func (*CommentLike) TableName() string {
	return TableNameCommentLike
}
