// Code generated by "stringer -type Gender -linecomment"; DO NOT EDIT.

package consts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MALE-0]
	_ = x[FEMALE-1]
	_ = x[UNKNOWN-2]
}

const _Gender_name = "男女其他"

var _Gender_index = [...]uint8{0, 3, 6, 12}

func (i Gender) String() string {
	if i < 0 || i >= Gender(len(_Gender_index)-1) {
		return "Gender(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gender_name[_Gender_index[i]:_Gender_index[i+1]]
}
