// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	service "github.com/cold-runner/skylark/biz/application/user"
	"github.com/cold-runner/skylark/biz/infrastructure/errCode"
	"github.com/cold-runner/skylark/biz/infrastructure/log"
	user "github.com/cold-runner/skylark/biz/model/user"
)

// Register .
// @router /register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	routerPath := string(c.URI().LastPathSegment())

	hlog.Debugf(log.ROUTE_PATH, routerPath)

	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		errCode.ResponseValidationFailed(c, err)
		return
	}

	resp, err := service.Register(c, &req)
	if err != nil {
		errCode.ResponseFailed(c)
		hlog.Errorf(log.REQUEST_FAILED+log.EXTRA_ERROR_INFO, routerPath, c.Errors.Last())
		return
	}

	hlog.Debugf(log.REQUEST_SUCCESSFUL, routerPath)
	c.JSON(consts.StatusOK, resp)
}

// PasswordLogin .
// @router /login/password [GET]
func PasswordLogin(ctx context.Context, c *app.RequestContext) {
	routerPath := string(c.URI().LastPathSegment())

	hlog.Debugf(log.ROUTE_PATH, routerPath)

	var err error
	var req user.PasswordLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		errCode.ResponseValidationFailed(c, err)
		return
	}

	resp := new(user.PasswordLoginResp)

	hlog.Debugf(log.REQUEST_SUCCESSFUL, routerPath)
	c.JSON(consts.StatusOK, resp)
}

// PhoneLogin .
// @router /login/phone [GET]
func PhoneLogin(ctx context.Context, c *app.RequestContext) {
	routerPath := string(c.URI().LastPathSegment())

	hlog.Debugf(log.ROUTE_PATH, routerPath)

	var err error
	var req user.PhoneLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		errCode.ResponseValidationFailed(c, err)
		return
	}

	resp := new(user.PhoneLoginResp)

	hlog.Debugf(log.REQUEST_SUCCESSFUL, routerPath)
	c.JSON(consts.StatusOK, resp)
}

// SendSmsCode .
// @router /sendSmsCode [GET]
func SendSmsCode(ctx context.Context, c *app.RequestContext) {
	routerPath := string(c.URI().LastPathSegment())

	hlog.Debugf(log.ROUTE_PATH, routerPath)

	var err error
	var req user.SendSmsCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		errCode.ResponseValidationFailed(c, err)
		return
	}

	resp := new(user.SendSmsCodeRes)

	hlog.Debugf(log.REQUEST_SUCCESSFUL, routerPath)
	c.JSON(consts.StatusOK, resp)
}

// GetUserInfo .
// @router /user/getInfoById [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	routerPath := string(c.URI().LastPathSegment())

	hlog.Debugf(log.ROUTE_PATH, routerPath)

	var err error
	var req user.GetUserInfoByIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		errCode.ResponseValidationFailed(c, err)
		return
	}

	resp := new(user.GetUserInfoByIdRes)

	hlog.Debugf(log.REQUEST_SUCCESSFUL, routerPath)
	c.JSON(consts.StatusOK, resp)
}
