// Code generated by "stringer -type College -linecomment"; DO NOT EDIT.

package consts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MARXIST-0]
	_ = x[SOCIOLOGY-1]
	_ = x[NEWS_AND_PROPAGATION-2]
	_ = x[FOREIGN_LANGUAGE-3]
	_ = x[DRAMATIC_ART-4]
	_ = x[LIFE_SCIENCE-5]
	_ = x[PALEONTOLOGY-6]
	_ = x[TOURISM_MANAGEMENT-7]
	_ = x[INTERNATIONAL_BUSINESS-8]
	_ = x[EDUCATION_SCIENCE-9]
	_ = x[SPORTS_SCIENCE-10]
	_ = x[MUSIC-11]
	_ = x[MATHEMATICS_AND_SYSTEMS_SCIENCE-12]
	_ = x[CHEMISTRY_AND_CHEMICAL_ENGINEERING-13]
	_ = x[SOFTWARE-14]
	_ = x[LAW-15]
	_ = x[PRESCHOOL_AND_ELEMENTARY_EDUCATION-16]
	_ = x[LITERATURE-17]
	_ = x[FINE_ARTS_AND_DESIGN-18]
	_ = x[PHYSICAL_SCIENCE_AND_TECHNOLOGY-19]
	_ = x[CEREALS-20]
	_ = x[MANAGEMENT-21]
}

const _College_name = "马克思主义学院生命科学学院新闻与传播学院外国语学院戏剧艺术学院生命科学学院古生物学院旅游管理学院国际商学院教育科学学院体育科学学院音乐学院数学与系统科学学院化学化工学院软件学院法学院学前与初等教育学院文学院美术与设计学院物理科学与技术学院粮食学院管理学院"

var _College_index = [...]uint16{0, 21, 39, 60, 75, 93, 111, 126, 144, 159, 177, 195, 207, 234, 252, 264, 273, 300, 309, 330, 357, 369, 381}

func (i College) String() string {
	if i < 0 || i >= College(len(_College_index)-1) {
		return "College(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _College_name[_College_index[i]:_College_index[i+1]]
}
