// Code generated by hertz generator.

package article

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/limiter"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		gzip.Gzip(gzip.DefaultCompression),
		limiter.AdaptiveLimit(),
	}
}

func _getarticleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getarticlefeedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searcharticleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _articleMw() []app.HandlerFunc {
	// your code...
	return nil
}
