// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_gen

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNamePlate = "plate"

// Plate mapped from table <plate>
type Plate struct {
	ID        uuid.UUID      `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4();comment:自然主键" json:"id"`                // 自然主键
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`                         // 创建时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:deleted_at,priority:1;comment:删除时间（软删除）" json:"deleted_at"` // 删除时间（软删除）
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                                  // 更新时间
	Name      string         `gorm:"column:name;type:varchar(50);not null;uniqueIndex:plate_pk,priority:1;comment:板块名称" json:"name"`  // 板块名称
}

// TableName Plate's table name
func (*Plate) TableName() string {
	return TableNamePlate
}
