package consts

// Major 专业
type Major int

const (
	MAJOR_LAW Major = iota
	MAJOR_PALEONTOLOGY
	MAJOR_ADMINISTRATION
	MAJOR_LABOR_AND_SOCIAL_SECURITY
	MAJOR_INTERNATIONAL_ECONOMY_AND_TRADING
	MAJOR_FINANCE
	MAJOR_MARKETING
	MAJOR_LOGISTICS_MANAGEMENT
	MAJOR_CHEMISTRY_NORMAL
	MAJOR_ENERGY_CHEMICAL_ENGINEERING
	MAJOR_PEDAGOGY_NORMAL
	MAJOR_APPLIED_PSYCHOLOGY
	MAJOR_GRAIN_ENGINEERING
	MAJOR_FOOD_SCIENCE_AND_ENGINEERING
	MAJOR_TOURISM_MANAGEMENT
	MAJOR_HOTEL_MANAGEMENT
	MAJOR_HISTORY_NORMAL
	MAJOR_IDEOLOGICAL_AND_POLITICAL_EDUCATION_NORMAL
	MAJOR_FINE_ARTS_NORMAL
	MAJOR_VISUAL_COMMUNICATION_DESIGN
	MAJOR_ENVIRONMENTAL_DESIGN
	MAJOR_PUBLIC_ART
	MAJOR_PAINTING
	MAJOR_SOFTWARE_ENGINEERING
	MAJOR_NETWORK_ENGINEERING
	MAJOR_COMPUTER_SCIENCE_AND_TECHNOLOGY
	MAJOR_COMPUTER_SCIENCE_AND_TECHNOLOGY_NORMAL
	MAJOR_SOCIOLOGY
	MAJOR_SOCIAL_WORK
	MAJOR_BIOLOGICAL_SCIENCES_NORMAL
	MAJOR_ENVIRONMENTAL_ECOLOGICAL_ENGINEERING
	MAJOR_MATHEMATICS_AND_APPLIED_MATHEMATICS_NORMAL
	MAJOR_DATA_SCIENCE_AND_BIG_DATA_TECHNOLOGY
	MAJOR_PHYSICAL_EDUCATION
	MAJOR_SPORTS_TRAINING
	MAJOR_WUSHU_AND_NATIONAL_TRADITIONAL_SPORTS
	MAJOR_ENGLISH_NORMAL
	MAJOR_JAPANESE
	MAJOR_RUSSIAN
	MAJOR_FRENCH
	MAJOR_TRANSLATION
	MAJOR_GERMAN
	MAJOR_CHINESE_LANGUAGE_AND_LITERATURE_NORMAL
	MAJOR_TEACHING_CHINESE_TO_SPEAKERS_OF_OTHER_LANGUAGES_NORMAL
	MAJOR_PHYSICS_NORMAL
	MAJOR_ELECTRONIC_INFORMATION_ENGINEERING
	MAJOR_PERFORMANCE
	MAJOR_DANCE_PERFORMANCE
	MAJOR_MUSIC_PERFORMANCE_ART
	MAJOR_DRAMA_FILM_AND_TELEVISION_ART_DESIGN
	MAJOR_BROADCASTING_AND_HOSTING_ART
	MAJOR_JOURNALISM
	MAJOR_EDUCATIONAL_TECHNOLOGY_NORMAL
	MAJOR_INTERNET_AND_NEW_MEDIA
	MAJOR_RADIO_AND_TELEVISION_DIRECTOR
	MAJOR_PRESCHOOL_EDUCATION_NORMAL
	MAJOR_PRIMARY_EDUCATION_NORMAL
	MAJOR_MUSICOLOGY_NORMAL
	MAJOR_MUSIC_PERFORMANCE_MUSIC
)

var MajorList = map[string]Major{
	"法学":           MAJOR_LAW,
	"古生物学":         MAJOR_PALEONTOLOGY,
	"行政管理":         MAJOR_ADMINISTRATION,
	"劳动与社会保障":      MAJOR_LABOR_AND_SOCIAL_SECURITY,
	"国际经济与贸易":      MAJOR_INTERNATIONAL_ECONOMY_AND_TRADING,
	"金融学":          MAJOR_FINANCE,
	"市场营销":         MAJOR_MARKETING,
	"物流管理":         MAJOR_LOGISTICS_MANAGEMENT,
	"化学（师范）":       MAJOR_CHEMISTRY_NORMAL,
	"能源化学工程":       MAJOR_ENERGY_CHEMICAL_ENGINEERING,
	"教育学（师范）":      MAJOR_PEDAGOGY_NORMAL,
	"应用心理学（师范）":    MAJOR_APPLIED_PSYCHOLOGY,
	"粮食工程":         MAJOR_GRAIN_ENGINEERING,
	"食品科学与工程":      MAJOR_FOOD_SCIENCE_AND_ENGINEERING,
	"旅游管理":         MAJOR_TOURISM_MANAGEMENT,
	"酒店管理":         MAJOR_HOTEL_MANAGEMENT,
	"历史学（师范类）":     MAJOR_HISTORY_NORMAL,
	"思想政治教育（师范）":   MAJOR_IDEOLOGICAL_AND_POLITICAL_EDUCATION_NORMAL,
	"美术学（师范）":      MAJOR_FINE_ARTS_NORMAL,
	"视觉传达设计":       MAJOR_VISUAL_COMMUNICATION_DESIGN,
	"环境设计":         MAJOR_ENVIRONMENTAL_DESIGN,
	"公共艺术":         MAJOR_PUBLIC_ART,
	"绘画":           MAJOR_PAINTING,
	"软件工程":         MAJOR_SOFTWARE_ENGINEERING,
	"网络工程":         MAJOR_NETWORK_ENGINEERING,
	"计算机科学与技术":     MAJOR_COMPUTER_SCIENCE_AND_TECHNOLOGY,
	"计算机科学与技术（师范）": MAJOR_COMPUTER_SCIENCE_AND_TECHNOLOGY_NORMAL,
	"社会学":          MAJOR_SOCIOLOGY,
	"社会工作":         MAJOR_SOCIAL_WORK,
	"生物科学专业（师范）":   MAJOR_BIOLOGICAL_SCIENCES_NORMAL,
	"环境生态工程":       MAJOR_ENVIRONMENTAL_ECOLOGICAL_ENGINEERING,
	"数学与应用数学（师范）":  MAJOR_MATHEMATICS_AND_APPLIED_MATHEMATICS_NORMAL,
	"数据科学与大数据技术":   MAJOR_DATA_SCIENCE_AND_BIG_DATA_TECHNOLOGY,
	"体育教育":         MAJOR_PHYSICAL_EDUCATION,
	"运动训练":         MAJOR_SPORTS_TRAINING,
	"武术与民族传统体育":    MAJOR_WUSHU_AND_NATIONAL_TRADITIONAL_SPORTS,
	"英语（师范）":       MAJOR_ENGLISH_NORMAL,
	"日语":           MAJOR_JAPANESE,
	"俄语":           MAJOR_RUSSIAN,
	"法语":           MAJOR_FRENCH,
	"翻译":           MAJOR_TRANSLATION,
	"德语":           MAJOR_GERMAN,
	"汉语言文学（师范）":    MAJOR_CHINESE_LANGUAGE_AND_LITERATURE_NORMAL,
	"汉语国际教育（师范）":   MAJOR_TEACHING_CHINESE_TO_SPEAKERS_OF_OTHER_LANGUAGES_NORMAL,
	"物理学（师范）":      MAJOR_PHYSICS_NORMAL,
	"电子信息工程":       MAJOR_ELECTRONIC_INFORMATION_ENGINEERING,
	"表演":           MAJOR_PERFORMANCE,
	"舞蹈表演":         MAJOR_DANCE_PERFORMANCE,
	"音乐表演（戏剧艺术学院）": MAJOR_MUSIC_PERFORMANCE_ART,
	"戏剧影视美术设计":     MAJOR_DRAMA_FILM_AND_TELEVISION_ART_DESIGN,
	"播音与主持艺术":      MAJOR_BROADCASTING_AND_HOSTING_ART,
	"新闻学":          MAJOR_JOURNALISM,
	"教育技术学（师范）":    MAJOR_EDUCATIONAL_TECHNOLOGY_NORMAL,
	"网络与新媒体":       MAJOR_INTERNET_AND_NEW_MEDIA,
	"广播电视编导":       MAJOR_RADIO_AND_TELEVISION_DIRECTOR,
	"学前教育（师范）":     MAJOR_PRESCHOOL_EDUCATION_NORMAL,
	"小学教育（师范)":     MAJOR_PRIMARY_EDUCATION_NORMAL,
	"音乐学（师范）":      MAJOR_MUSICOLOGY_NORMAL,
	"音乐表演（音乐学院）":   MAJOR_MUSIC_PERFORMANCE_MUSIC,
}

func (m Major) String() string {
	switch m {
	case MAJOR_LAW:
		return "法学"
	case MAJOR_PALEONTOLOGY:
		return "古生物学"
	case MAJOR_ADMINISTRATION:
		return "行政管理"
	case MAJOR_LABOR_AND_SOCIAL_SECURITY:
		return "劳动与社会保障"
	case MAJOR_INTERNATIONAL_ECONOMY_AND_TRADING:
		return "国际经济与贸易"
	case MAJOR_FINANCE:
		return "金融学"
	case MAJOR_MARKETING:
		return "市场营销"
	case MAJOR_LOGISTICS_MANAGEMENT:
		return "物流管理"
	case MAJOR_CHEMISTRY_NORMAL:
		return "化学（师范）"
	case MAJOR_ENERGY_CHEMICAL_ENGINEERING:
		return "能源化学工程"
	case MAJOR_PEDAGOGY_NORMAL:
		return "教育学（师范）"
	case MAJOR_APPLIED_PSYCHOLOGY:
		return "应用心理学（师范）"
	case MAJOR_GRAIN_ENGINEERING:
		return "粮食工程"
	case MAJOR_FOOD_SCIENCE_AND_ENGINEERING:
		return "食品科学与工程"
	case MAJOR_TOURISM_MANAGEMENT:
		return "旅游管理"
	case MAJOR_HOTEL_MANAGEMENT:
		return "酒店管理"
	case MAJOR_HISTORY_NORMAL:
		return "历史学（师范类）"
	case MAJOR_IDEOLOGICAL_AND_POLITICAL_EDUCATION_NORMAL:
		return "思想政治教育（师范类）"
	case MAJOR_FINE_ARTS_NORMAL:
		return "美术学（师范）"
	case MAJOR_VISUAL_COMMUNICATION_DESIGN:
		return "视觉传达设计"
	case MAJOR_ENVIRONMENTAL_DESIGN:
		return "环境设计"
	case MAJOR_PUBLIC_ART:
		return "公共艺术"
	case MAJOR_PAINTING:
		return "绘画"
	case MAJOR_SOFTWARE_ENGINEERING:
		return "软件工程"
	case MAJOR_NETWORK_ENGINEERING:
		return "网络工程"
	case MAJOR_COMPUTER_SCIENCE_AND_TECHNOLOGY:
		return "计算机科学与技术"
	case MAJOR_COMPUTER_SCIENCE_AND_TECHNOLOGY_NORMAL:
		return "计算机科学与技术（师范）"
	case MAJOR_SOCIOLOGY:
		return "社会学"
	case MAJOR_SOCIAL_WORK:
		return "社会工作"
	case MAJOR_BIOLOGICAL_SCIENCES_NORMAL:
		return "生物科学专业（师范）"
	case MAJOR_ENVIRONMENTAL_ECOLOGICAL_ENGINEERING:
		return "环境生态工程"
	case MAJOR_MATHEMATICS_AND_APPLIED_MATHEMATICS_NORMAL:
		return "数学与应用数学（师范）"
	case MAJOR_DATA_SCIENCE_AND_BIG_DATA_TECHNOLOGY:
		return "数据科学与大数据技术"
	case MAJOR_PHYSICAL_EDUCATION:
		return "体育教育"
	case MAJOR_SPORTS_TRAINING:
		return "运动训练"
	case MAJOR_WUSHU_AND_NATIONAL_TRADITIONAL_SPORTS:
		return "武术与民族传统体育"
	case MAJOR_ENGLISH_NORMAL:
		return "英语（师范）"
	case MAJOR_JAPANESE:
		return "日语"
	case MAJOR_RUSSIAN:
		return "俄语"
	case MAJOR_FRENCH:
		return "法语"
	case MAJOR_TRANSLATION:
		return "翻译"
	case MAJOR_GERMAN:
		return "德语"
	case MAJOR_CHINESE_LANGUAGE_AND_LITERATURE_NORMAL:
		return "汉语言文学（师范）"
	case MAJOR_TEACHING_CHINESE_TO_SPEAKERS_OF_OTHER_LANGUAGES_NORMAL:
		return "汉语国际教育（师范）"
	case MAJOR_PHYSICS_NORMAL:
		return "物理学（师范）"
	case MAJOR_ELECTRONIC_INFORMATION_ENGINEERING:
		return "电子信息工程"
	case MAJOR_PERFORMANCE:
		return "表演"
	case MAJOR_DANCE_PERFORMANCE:
		return "舞蹈表演"
	case MAJOR_MUSIC_PERFORMANCE_ART:
		return "音乐表演（戏剧艺术学院）"
	case MAJOR_DRAMA_FILM_AND_TELEVISION_ART_DESIGN:
		return "戏剧影视美术设计"
	case MAJOR_BROADCASTING_AND_HOSTING_ART:
		return "播音与主持艺术"
	case MAJOR_JOURNALISM:
		return "新闻学"
	case MAJOR_EDUCATIONAL_TECHNOLOGY_NORMAL:
		return "教育技术学（师范）"
	case MAJOR_INTERNET_AND_NEW_MEDIA:
		return "网络与新媒体"
	case MAJOR_RADIO_AND_TELEVISION_DIRECTOR:
		return "广播电视编导"
	case MAJOR_PRESCHOOL_EDUCATION_NORMAL:
		return "学前教育（师范）"
	case MAJOR_PRIMARY_EDUCATION_NORMAL:
		return "小学教育（师范)"
	case MAJOR_MUSICOLOGY_NORMAL:
		return "音乐学（师范）"
	case MAJOR_MUSIC_PERFORMANCE_MUSIC:
		return "音乐表演（音乐学院）"
	default:
		return ""
	}
}

func (m Major) CheckFuncName() string {
	return "major"
}
