// Code generated by "stringer -type Province -linecomment"; DO NOT EDIT.

package consts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZHE_JIANG-0]
	_ = x[SHANG_HAI-1]
	_ = x[BEI_JING-2]
	_ = x[TIAN_JIN-3]
	_ = x[CHONG_QING-4]
	_ = x[HEI_LONG_JIANG-5]
	_ = x[JI_LIN-6]
	_ = x[LIAO_NING-7]
	_ = x[NEI_MENG_GU-8]
	_ = x[HE_BEI-9]
	_ = x[XIN_JIANG-10]
	_ = x[GAN_SU-11]
	_ = x[QING_HAI-12]
	_ = x[SH_AN_XI-13]
	_ = x[NING_XIA-14]
	_ = x[HE_NAN-15]
	_ = x[SHAN_DONG-16]
	_ = x[SHAN_XI-17]
	_ = x[AN_HUI-18]
	_ = x[HU_BEI-19]
	_ = x[HU_NAN-20]
	_ = x[JIANG_SU-21]
	_ = x[SI_CHUAN-22]
	_ = x[GUI_ZHOU-23]
	_ = x[YUN_NAN-24]
	_ = x[GUANG_XI-25]
	_ = x[XI_ZANG-26]
	_ = x[JIANG_XI-27]
	_ = x[GUANG_DONG-28]
	_ = x[FU_JIAN-29]
	_ = x[TAI_WAN-30]
	_ = x[HAI_NAN-31]
	_ = x[XIANG_GANG-32]
	_ = x[AO_MEN-33]
}

const _Province_name = "浙江上海北京天津重庆黑龙江吉林辽宁内蒙古河北新疆甘肃青海陕西宁夏河南山东山西安徽湖北湖南江苏四川贵州云南广西西藏江西广东福建台湾海南香港澳门"

var _Province_index = [...]uint8{0, 6, 12, 18, 24, 30, 39, 45, 51, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 132, 138, 144, 150, 156, 162, 168, 174, 180, 186, 192, 198, 204, 210}

func (i Province) String() string {
	if i < 0 || i >= Province(len(_Province_index)-1) {
		return "Province(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Province_name[_Province_index[i]:_Province_index[i+1]]
}
